# Generated by Django 5.2.18 on 2026-10-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('track', models.CharField(max_length=40)),
                ('message', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_emailed', models.BooleanField(default=False)),
                ('confirmation_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
